# Generated by Django 6.0.1 on 2026-01-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="pH",
            field=models.IntegerField(null=True),
        ),
    ]
